<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>RNS.Companion</AssemblyName>
    <RootNamespace>RnsCompanion</RootNamespace>
    <Product>RNS Companion</Product>
    <Description>RNS — Набор игроков на сервера Squad (rnserver.ru)</Description>
    <Version>1.4.2</Version>
    <AssemblyVersion>1.4.2.0</AssemblyVersion>
    <FileVersion>1.4.2.0</FileVersion>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Presets\GameUserSettings.low.ini" />
    <Resource Include="Assets\logo.png" />
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

</Project>
