;METADATA=(Diff=true, UseCommands=true)
[Internationalization]
Language=en-US
Locale=en-US

[/Script/Squad.SQGameUserSettings]
bShowDiffVerServers=True
bShowEmptyServers=True
bShowReservedSlots=True
FilterMaxPing=9999
MasterVolume=0.000000
EffectsVolume=0.494500
UIVolume=0.067400
MusicVolume=0.000000
LocalVoIPVolume=0.400700
CommandVoIPVolume=0.484100
CommandVoIPSide=0.000000
VoiceSide=0.000000
UnfocusedVolumeMultiplier=0.471200
GraphicsQuality=0
ScreenSharpening=(Value=1056964608)
ScreenPercentage=(Value=10)
MaxAnisotropy=(Value=4)
ScopeUpdateRate=(Value=0)
ScopeResolutionScale=(Value=1120403456)
FSRQuality=(Value=0)
FSRSharpness=(Value=1060320051)
DLSSMode=Off
MaterialQuality=(Value=0)
CrouchMode=Toggle
ADSMode=Toggle
LeanMode=Hold
FreelookMode=Hold
SprintMode=Hold
FreelookSensitivity=4.000000
Version=5
SquadIncrementalVersion=1
bClientAutoRecord=False
NumberAutoRecordedGames=5
ControlsPresetName=INVTEXT("Default")
HZBOcclusion=(Value=0)
TextureStreamPoolSizeStorage=(Value=1)
bCompassBackgroundEnabled=False
bCompassTopViewEnabled=False
bWeaponModelBlurDisabled=False
GlobalSensitivity=0.110000
SteadyAimSensitivity=1.000000
bHelicopterInvertMousePitch=False
HelicopterPitchSensitivity=4.000000
bUncapTexturePoolSize=True
HelicopterRollSensitivity=4.000000
SoldierSensitivity=1.000000
SoldierZoomSensitivities=((1.000000, 1.000000),(2.000000, 0.500000),(3.000000, 0.330000),(4.000000, 0.250000),(6.000000, 0.170000),(8.000000, 0.130000),(12.000000, 0.080000))
VehicleSensitivity=1.000000
PostFX_Brightness=1.000000
PostFX_Contrast=1.000000
PostFX_Saturation=1.000000
FoliageMinLOD=(Value=3)
VehicleZoomSensitivities=((1.000000, 1.000000),(4.000000, 0.500000))
bFreelookRecentersWeapon=False
bShowFullServers=True
bShowModdedServers=True
bShowWhitelistedMods=True
bShowLicensedServers=True
MenuFrameRateLimit=10.000000
BrowserSearchTags=mode_invasion
BrowserSearchTags=mode_aas
BrowserSearchTags=mode_raas
BrowserSearchTags=mode_destruction
BrowserSearchTags=mode_tc
BrowserSearchTags=mode_insurgency
BrowserSearchTags=mode_seed
BrowserSearchTags=mode_skirmish
BrowserSearchTags=mode_training
BrowserSearchTags=language_ru
QPPreferedLanguage=en
QPGameModes=Advance and Secure
QPGameModes=Random AAS
QPGameModes=Insurgency
QPGameModes=Invasion
QPGameModes=Seed
QPGameModes=Territory Control
QPGameModes=Skirmish
QPGameModes=Training
QPGameModes=Destruction
QPSearchTags=language_ru
AmbientOcclusion=(Value=0)
SelectedFrameGeneration=NONE
NISSharpness=0.000000
DLSSFrameGenerationMode=Off
ReflexMode=Off
TSRSampleCount=(Value=32)
TSRFlickeringPeriod=(Value=0)
OceanQuality=(Value=0)
WakeSim=(Value=0)
LensFlares=(Value=0)
Reflections=(Value=0)
SkeletalMeshLODBias=(Value=3)
EquippedEmotes=/Game/Art/Soldier_Animations/BazaarEmotes/EmoteData/Emote_Hello.Emote_Hello
EquippedEmotes=/Game/Art/Soldier_Animations/BazaarEmotes/EmoteData/Gesture_PointForward.Gesture_PointForward
EquippedEmotes=/Game/Art/Soldier_Animations/BazaarEmotes/EmoteData/Gesture_MoveOut.Gesture_MoveOut
EquippedEmotes=/Game/Art/Soldier_Animations/BazaarEmotes/EmoteData/Gesture_WeaponInspection.Gesture_WeaponInspection
SquadVoiceVolume=0.098600
bApplyBiasWhileNonLeader=False
JoyStickConfigurations=((Pitch, ()),(Roll, ()),(Yaw, ()),(Collective, ()))
bAlwaysFreeLook=False
SelectedSpecialCommendation=None
StreamerModeMask=0
SquadSettingsVersion=12
bUseVSync=False
bUseDynamicResolution=False
ResolutionSizeX=640
ResolutionSizeY=480
LastUserConfirmedResolutionSizeX=640
LastUserConfirmedResolutionSizeY=480
WindowPosX=-1
WindowPosY=-1
FullscreenMode=2
LastConfirmedFullscreenMode=2
PreferredFullscreenMode=2
LastConfirmedAudioQualityLevel=3
FrameRateLimit=5.000000
DesiredScreenWidth=640
DesiredScreenHeight=480
LastRecommendedScreenWidth=-1.000000
LastRecommendedScreenHeight=-1.000000
bUseHDRDisplayOutput=False
HDRDisplayOutputNits=1000
bMotionBlur=False
bFilmGrain=False
bAmbientOcclusion=False
bBloom=False
XESSMode=Off
LastUserConfirmedDesiredScreenWidth=640
LastUserConfirmedDesiredScreenHeight=480

[ScalabilityGroups]
sg.ResolutionQuality=10
sg.ViewDistanceQuality=0
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.GlobalIlluminationQuality=0
sg.ReflectionQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=0
sg.EffectsQuality=0
sg.FoliageQuality=0
sg.ShadingQuality=0
sg.LandscapeQuality=0

[/Script/Engine.GameUserSettings]
bUseDesiredScreenHeight=False
